NovaCare/urls.py
from django.contrib import admin
from django.urls import path, include

from main_app import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('emergency/services/', views.emergency_services, name='emergency_services'),
    path('inpatient/services/', views.inpatient_services, name='inpatient_services'),
    path('outpatient/services/', views.outpatient_services, name='outpatient_services'),
    path('surgical/services/', views.surgical_services, name='surgical_services'),
    path('maternity/services/', views.maternity_services, name='maternity_services'),
    path('careers/', views.careers, name='careers'),


    path('novacare/', include('user_management.urls')),
    path('novacare/', include('payments_app.urls')),

    path('admin/', admin.site.urls),
]

payments_app/urls.py
from django.urls import path
from payments_app import views

app_name = 'payments_app'


urlpatterns = [
    path('payment/', views.payment_page, name='payment_page'),
    path('payment/<int:id>/', views.payment, name='payment'),
    path('callback/', views.callback, name='trigger'),
]

user_management/urls.py
from django.urls import  path
from user_management import views

from NovaCare import settings
from django.conf.urls.static import static

app_name = 'user_management'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.signout_user, name='logout'),

    path('password-reset/', views.password_reset_request, name='password_reset_request'),
    path('reset-password-confirm/<str:token>/', views.password_reset_confirm, name='password_reset_confirm'),


    path('portal/', views.dashboard, name='dashboard'),
    path('staff/', views.staff_dashboard, name='staff_dashboard'),
    path('users/', views.patient_dashboard, name='patient_dashboard'),

    path('user/details/<int:user_id>', views.user_details, name='user_details'),
    path('user/add/details', views.add_details, name='add_details'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/models.py
from django.db import models
from django.contrib.auth.models import User

import os
import uuid

def generate_unique_name(instance, filename):
    name = uuid.uuid4()
    full_filename = f'{name}-{filename}'
    return os.path.join("profile_pictures", full_filename)

# Create your models here.
class Details(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default='-')
    last_name = models.CharField(max_length=50, default='-')
    phone_number = models.CharField(max_length=15, default='-')
    dob = models.DateField(default='2025-01-01')
    identity_type = models.CharField(max_length=30, default='-')
    identity_number = models.CharField(max_length=30, default='-')
    gender = models.CharField(max_length=6, default='-')
    profile_pic = models.ImageField(upload_to=generate_unique_name, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name}-{self.last_name}'
    
    class Meta:
        db_table = 'Personal_Details'

user_management/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,  get_object_or_404
from user_management.app_forms import LoginForm, PasswordResetRequestForm, SetNewPasswordForm, CustomUserCreationForm, PersonalDetailsForm

from django.core.signing import TimestampSigner, SignatureExpired, BadSignature
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.urls import reverse
from django.core.mail import EmailMultiAlternatives
from django.utils import timezone

from user_management.models import Details


signer = TimestampSigner() # creates signed tokens


# Create your views here.
def login_user(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {"form": form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('user_management:dashboard')
        messages.error(request, "Invalid username or password")
        return render(request, "login.html", {"form": form})

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account creation for {username} was successful!')
            return redirect('user_management:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})

def signout_user(request):
    logout(request)
    return redirect('home')

# Request reset via email
def password_reset_request(request):
    if request.method == "POST":
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
                token = signer.sign(user.pk) # sign user id
                reset_link = request.build_absolute_uri(
                    reverse('user_management:password_reset_confirm', args=[token])
                )

                html_content = f"""
                    <div>
                        <h2 style='color: #004f71; text-align: center;'> NovaCare </h2>

                        <p> Hi <strong>{user.username}</strong>, </p>

                        <p>
                            You requested a password reset. Click the link below to set a new password:
                        </p>

                        <p style='margin: 20px 0;'>
                            <a href="{reset_link}" style='display: inline-block; 
                                                   padding: 10px 15px; background-color: #004f71; color: white; 
                                                   text-decoration: none; border-radius: 5px;'>
                                Reset Password
                            </a>
                        </p>

                        <p>
                            If the above button doesn't work, copy and paste the following link into your browser:
                        </p>

                        <p>
                            <a href="{reset_link}">{reset_link}</a>
                        </p>

                        <p>
                            The link is valid for 30 minutes only.
                        </p>

                        <hr>

                        <p>
                            If you did not request a password reset, please ignore this email. <br>
                            &copy; {timezone.now().year} NovaCare. All rights reserved.
                        </p>
                    </div>
                """

                subject = "Password Reset Request"
                from_email = settings.DEFAULT_FROM_EMAIL
                to = [email]

                message = EmailMultiAlternatives(subject, "", from_email, to)
                message.attach_alternative(html_content, "text/html")
                message.send()


                messages.success(request, f'Your password reset link has been sent to {email}.')
                return redirect('user_management:login')
            except User.DoesNotExist:
                messages.error(request, f'No user found with the email {email}.')
    else:
        form = PasswordResetRequestForm()
    return render(request, "password_reset_request.html", {'form': form})


# Reset password using token
def password_reset_confirm(request, token):
    try:
        user_id = signer.unsign(token, max_age=3600) # token id valid for 1 hour
        user = User.objects.get(pk=user_id)
    except (BadSignature, SignatureExpired, User.DoesNotExist):
        messages.error(request, 'Invalid or expired reset link.')
        return redirect("user_management:password_reset_request")

    if request.method == "POST":
        form = SetNewPasswordForm(request.POST)
        if form.is_valid():
            user_password = form.cleaned_data["new_password"]
            user.password = make_password(user_password)
            user.save()
            messages.success(request, 'Password updated successfully!')
            return redirect('user_management:login')
    else:
        form = SetNewPasswordForm()
    return render(request, 'password_reset_confirm.html', {'form': form})



@login_required
def dashboard(request):
    if request.user.is_staff:
        return redirect('user_management:staff_dashboard')
    else:
        return redirect('user_management:patient_dashboard')


def patient_dashboard(request):
    context = {
        'username': request.user.username,
    }
    return render(request, 'patient_dashboard.html', context)

def staff_dashboard(request):
    context = {
        'username': request.user.username,
    }
    return render(request, 'staff_dashboard.html', context)


@login_required
def user_details(request, user_id):
    user = get_object_or_404(User, id=user_id)
    details = (Details.objects.filter(user=user).order_by('-updated_at').first())
    if not details:
        details = Details.objects.create(user=user)
    return render(request, 'user_details.html', {'user': user, 'details': details})


@login_required
def add_details(request):
    try:
        details = Details.objects.filter(user=request.user).order_by('-updated_at').first()
    except Details.DoesNotExist:
        details= None

    if request.method == "POST":
        form = PersonalDetailsForm(request.POST, request.FILES, instance=details)
        if form.is_valid():
            personal_details = form.save(commit=False)
            personal_details.user = request.user
            personal_details.save()
            messages.success(request, "Details updated successfully")
            return redirect('user_management:dashboard')
    else:
        form = PersonalDetailsForm(instance=details)
    return render(request, 'user_update_form.html', {"form": form})

user_management/templates/login.html
{% load static %}
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> NovaCare - Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <link rel="stylesheet" href="{% static 'CSS/event_form.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/nova_forms.css' %}">
        <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
    </head>

    <body class="login-page">
        <div class="container">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                    <p>{{ message }}</p>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>


        <div class="container vh-100 d-flex justify-content-center align-items-center">
            <div class="row justify-content-center w-100">
                <div class="col-12 col-sm-8 col-md-6 col-lg-4">
                    <form action="{% url 'user_management:login' %}" method="post" class="shadow px-3 py-4 create-form mx-auto">
                        <h2 class="company-name text-center">NovaCare</h2>
                        {% csrf_token %}
                        {{ form | crispy }}

                        <div class="mb-2 text-center">
                            <a href="{% url 'user_management:password_reset_request' %}" class="create-account">
                                 Forgot password?</a>
                        </div>

                        <button class="btn btn-primary rounded-0 w-100">Sign In</button>

                        <div class="text-center mt-2">
                            <a href="{% url 'user_management:register' %}" class="create-account">
                            Not a member? Signup now</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

user_management/templates/password_reset_confirm.html
{% load static %}
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NovaCare</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
    <link rel="stylesheet" href="{% static 'CSS/password_reset_form.css' %}">
</head>

<body class="password-update-page">
    <div class="container">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                <p>{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
   </div>


    <div class="container vh-100 d-flex justify-content-center align-items-center">
        <div class="row justify-content-center w-100">
            <div class="col-sm-5">
                <form method="post" class="shadow px-3 py-4 update-form">
                    <h2 class="company-name text-center">NovaCare</h2>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-primary rounded-0 w-100" type="submit">Update Password</button>
                </form>
            </div>
        </div>
   </div>
</body>
</html>

user_management/templates/patient_dashboard.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
            <link rel="stylesheet" href="{% static 'CSS/Dashboard.css' %}">
            <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
            <title>Patient Dashboard</title>
        </head>
        <body>
            <div class="container">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                        <p>{{ message }}</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>

            
            <div class="container users d-flex">
                <div class="container mt-3 navigation">
                    <div class="username d-flex justify-content-center align-items-center text-dark">
                        <img src="{% static 'Images/nova.jpeg' %}" alt="novacare logo" class="w-25 h-25 me-2 rounded">
                        <p class="text-center mt-3 mb-3">NovaCare</p>
                    </div>

                    <div class="navigation-links d-flex justify-content-center">
                        <ul class="nav flex-column pt-2">
                            <li class="nav-item">
                                <a href="{% url 'user_management:user_details' user.id %}" class="nav-link">
                                    <img src="{% static 'Images/user-circle.png' %}" alt="user icon" class="icon">
                                    Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <img src="{% static 'Images/envelope.png' %}" alt="message icon" class="icon">
                                    Messages
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'payments_app:payment_page' %}" class="nav-link">
                                    <img src="{% static 'Images/credit-card-alt.png' %}" alt="credit card icon" class="icon">
                                    Payments
                                </a>
                            </li>
                            <li class="nav-item pt-3 mt-2">
                                <a href="{% url 'user_management:logout' %}" class="nav-link">
                                    <img src="{% static 'Images/arrow-out-left-square-half.png' %}" class="logout-icon" alt="logout icon">
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="container info-container">
                    <div class="container welcome mt-5 ms-3">
                        <h3>Hello {{ username }},</h3>
                    </div>

                    <div class="container user-information w-75 ms-4 pt-3">
                        <div class="row">
                            <div class="col-sm-4 mb-2 user-info bg-white p-2 me-1 rounded">
                                <a href="#" class="nav-link text-center">
                                    <img src="{% static 'Images/form.png' %}" alt="user icon" class="icon">
                                    Medical Records
                                </a>
                            </div>

                            <div class="col-sm-4 mb-2 user-info bg-white p-2 rounded">
                                <a href="#" class="nav-link text-center">
                                    <img src="{% static 'Images/calendar-event.png' %}" alt="calender icon" class="icon">
                                    Appointments
                                </a>
                            </div>

                            <div class="col-sm-4 mb-2 user-info bg-white p-2 rounded">
                                <a href="#" class="nav-link text-center">
                                    <img src="{% static 'Images/bell.png' %}" alt="bell icon" class="icon">
                                    Notifications
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="container information ms-3 pt-2 d-flex">
                        <div class="info bg-white p-4 w-100 d-flex justify-content-center rounded">
                            <h3 class="vision">Your Health, Our Commitment</h3>
                        </div>
                    </div>

                     <div class="container information ms-3 pt-3 d-flex h-50">
                        <div class="info bg-white p-4 w-100 d-flex justify-content-center rounded">
                            <h3 class="vision">Your Health, Our Commitment</h3>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>

user_management/templates/register.html
{% load static %}
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NovaCare - Sign Up</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
    <link rel="stylesheet" href="{% static 'CSS/nova_forms.css' %}">
    <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
</head>
<body class="register-page">
    <div class="container vh-100 d-flex justify-content-center align-items-center">
        <div class="row justify-content-center w-100">
            <div class="col-sm-6">
                <form action="{% url 'user_management:register' %}" method="post" class="shadow px-3 py-4 create-form">
                    <h2 class="company text-center">NovaCare</h2>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-primary rounded-0 w-100">Sign Up</button>
                </form>
            </div>
        </div>
   </div>
</body>
</html>

user_management/templates/staff_dashboard.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
            <link rel="stylesheet" href="{% static 'CSS/Dashboard.css' %}">
            <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
            <title>Staff Dashboard</title>
        </head>
        <body>
            <div class="container">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                        <p>{{ message }}</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>

            
            <div class="container users d-flex">
                <div class="mt-3 navigation">
                    <div class="username d-flex justify-content-center align-items-center text-dark">
                        <img src="{% static 'Images/nova.jpeg' %}" alt="novacare logo" class="w-25 h-25 me-2  rounded">
                        <p class="text-center mt-3 mb-3">NovaCare</p>
                    </div>

                    <div class="navigation-links d-flex justify-content-center">
                        <ul class="nav flex-column pt-2">
                            <li class="nav-item">
                                <a href="{% url 'user_management:user_details' user.id %}" class="nav-link">
                                    <img src="{% static 'Images/user-circle.png' %}" alt="user icon" class="icon">
                                    Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <img src="{% static 'Images/envelope.png' %}" alt="message icon" class="icon">
                                    Messages
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <img src="{% static 'Images/badge-info.png' %}" alt="clipboard icon" class="icon">
                                    Status
                                </a>
                            </li>
                            <li class="nav-item pt-3 mt-2">
                                <a href="{% url 'user_management:logout' %}" class="nav-link">
                                    <img src="{% static 'Images/arrow-out-left-square-half.png' %}" class="logout-icon" alt="logout icon">
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="container info-container">
                    <div class="container welcome mt-5 ms-3">
                        <h3>Hello {{ username }},</h3>
                    </div>

                    <div class="container user-information w-75 ms-4 pt-3">
                        <div class="row">
                            <div class="col-sm-4 mb-2 user-info bg-white p-2 me-1 rounded">
                                <a href="#" class="nav-link text-center">
                                    <img src="{% static 'Images/clock-3.png' %}" alt="user icon" class="icon">
                                    Work Schedule
                                </a>
                            </div>

                            <div class="col-sm-4 mb-2 user-info bg-white p-2 rounded">
                                <a href="#" class="nav-link text-center">
                                    <img src="{% static 'Images/calendar-event.png' %}" alt="calender icon" class="icon">
                                    Appointments
                                </a>
                            </div>

                            <div class="col-sm-4 mb-2 user-info bg-white p-2 rounded">
                                <a href="#" class="nav-link text-center">
                                     <img src="{% static 'Images/bell.png' %}" alt="bell icon" class="icon">
                                    Notifications
                                </a>
                            </div>
                        </div>
                    </div>


                    <div class="container information ms-3 pt-2 d-flex">
                        <div class="info bg-white p-4 w-100 d-flex justify-content-center rounded">
                            <h3 class="vision">Your Health, Our Commitment</h3>
                        </div>
                    </div>

                    <div class="container information ms-3 pt-3 d-flex h-50">
                        <div class="info bg-white p-4 w-100 d-flex justify-content-center rounded">
                            <h3 class="vision">Your Health, Our Commitment</h3>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>

user_management/templates/user_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personal Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/user_details.css' %}">
</head>
<body>
    <div class="container-fluid d-flex justify-content-center top-banner">
        <div class="banner" id="banner">
            <img src="{% static 'Images/nova.jpeg' %}" alt="logo" class="img-fluid banner-img" width="150px" height="150px">
        </div>
    </div>
    <div class="container personal-details">
        <div class="row mt-3">
            <div class="col-sm-4 profile">
                <h4 class="heading text-center">User Profile</h4>
                {% if user.profile_pic %}
               	    <img src="{{ user.profile_pic.url }}" alt="logo" 
                     class="img-fluid mx-auto d-block rounded-circle" style="height: 178px; width: 178px;">
               {% else %}
               	    <img src="{% static 'Images/logo.png' %}" alt="logo" 
                     class="img-fluid mx-auto d-block rounded-circle" style="height: 178px; width: 178px;">
               {% endif %}
            </div>
            <div class="col-sm-8">
                <h4 class="heading">Personal Information</h4>
                <table class="table">
                    <tr>
                        <th>Identification Type:</th>
                        <td>{{ details.identity_type }}</td>
                    </tr>
                    <tr>
                        <th>ID/Passport/Birth certificate:</th>
                        <td>{{ details.identity_number }}</td>
                    </tr>
                    <tr>
                        <th>First Name:</th>
                        <td>{{ details.first_name }}</td>
                    </tr>
                    <tr>
                        <th>Last Name:</th>
                        <td>{{ details.last_name }}</td>
                    </tr>
                    <tr>
                        <th>Gender:</th>
                        <td>{{ details.gender }}</td>
                    </tr>
                    <tr>
                        <th>Date of Birth:</th>
                        <td>{{ details.dob }}</td>
                    </tr>
                    <tr>
                        <th>Phone Number:</th>
                        <td>{{ details.phone_number }}</td>
                    </tr>
                    <tr>
                        <th>Email:</th>
                        <td>{{ details.user.email }}</td>
                    </tr>
                </table>

                <div class="update-btn d-flex justify-content-center">
                    <a href="{% url 'user_management:add_details'%}" class="btn btn-primary btn-sm">
                        <img src="{% static 'Images/edit .png' %}" alt="edit icon">
                        Update Profile
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="dashboard">
        <div class="dashboard-btn">
            <a href="{% url 'user_management:dashboard' %}" class="btn btn-primary">
                <img src="{% static 'Images/arrow-left-stroke.png' %}" alt="left arrow icon">
                Back to Dashboard
            </a>
        </div>
    </div>
</body>
</html>

user_management/templates/user_update_form.html
{% load static %}
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
</head>
<body>
    <div class="container">
       <div class="row justify-content-center">
            <div class="col-sm-4 border px-3 py-3 mt-3">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-primary w-100">Update Details</button>
                </form>
            </div>
       </div>
    </div>
</body>
</html>