NovaCare/urls.py
from django.contrib import admin
from django.urls import path, include

from main_app import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('emergency/services/', views.emergency_services, name='emergency_services'),
    path('inpatient/services/', views.inpatient_services, name='inpatient_services'),
    path('outpatient/services/', views.outpatient_services, name='outpatient_services'),
    path('surgical/services/', views.surgical_services, name='surgical_services'),
    path('maternity/services/', views.maternity_services, name='maternity_services'),
    path('careers/', views.careers, name='careers'),


    path('novacare/', include('user_management.urls')),
    path('novacare/', include('payments_app.urls')),

    path('admin/', admin.site.urls),
]

payments_app/urls.py
from django.urls import path
from payments_app import views

app_name = 'payments_app'


urlpatterns = [
    path('payment/', views.payment_page, name='payment_page'),
    path('payment/<int:id>/', views.payment, name='payment'),
    path('callback/', views.callback, name='trigger'),
]

payments_app/models.py
from django.db import models
from user_management.models import Details


# Create your models here.
class Payment(models.Model):
    details = models.ForeignKey(Details, on_delete=models.CASCADE)
    merchant_request_id = models.CharField(max_length=100)
    checkout_request_id = models.CharField(max_length=100)
    code = models.CharField(max_length=30, null=True)
    status = models.CharField(max_length=20, default="PENDING")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def _str_(self):
        return f"{self.details}-{self.code} - {self.status}"

    class Meta:
        db_table = 'payments'

    
class Amount(models.Model):
    fee = models.IntegerField()

    def __str__(self):
        return self.fee
    

    class Meta:
        db_table = 'amount'

payments_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django_daraja.mpesa.core import MpesaClient
from django.contrib import messages
from django.http import HttpResponse
import json

from user_management.models import Details

from payments_app.models import Payment

# Create your views here.

def payment_page(request):
    detail = Details.objects.filter(user=request.user).order_by('-updated_at').first()
    return render(request, 'payment_page.html', {'detail': detail})


def payment(request, id):
    details = get_object_or_404(Details, pk=id)
    charge = request.POST.get("amount")
    amount = int(charge)

    phone_number = details.phone_number


    cl = MpesaClient()
    phone_number = details.phone_number

    account_reference = "NovaCare"
    transaction_desc = 'Hospital bill'
    callback_url = 'https://flying-regularly-honeybee.ngrok-free.app/callback'
    response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
    if response.response_code == "0":
        payment = Payment.objects.create(details=details,
                                          merchant_request_id=response.merchant_request_id,
                                          checkout_request_id=response.checkout_request_id)
        payment.save()
        messages.success(request, f"Your payment was initiated successfully!")
    return redirect('user_management:dashboard')


def callback(request):
    repo = json.loads(request.body)
    data = repo.get['Body']['stkCallback']
    if data["ResultCode"] == "0":
        m_id = ["MerchantRequestID"]
        c_id = ["CheckoutRequestID"]
        code = ""
        item = data["CallbackMetadata"]["Item"]
        for i in item:
            name = i["Name"]
            if name == "MpesaReceiptNumber":
                code = i["Value"]
        registration = Details.objects.get(merchant_request_id=m_id, checkout_request_id=c_id)
        registration.code = code
        registration.status = "COMPLETED"
        registration.save()
    return HttpResponse("OK")

payments_app/templates/payment_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>NovaCare</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="icon" href="{% static 'Images/nova.jpeg' %}">
  <link rel="stylesheet" href="{% static 'CSS/payment_page.css' %}">
</head>
<body>
     <div class="container">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                <p>{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
     </div> 
     
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-4 border px-3 py-3 text-white create-form mt-3">
                <form action="{% url 'payments_app:payment' id=detail.id %}" method="post"  enctype="multipart/form-data">
                    <h2 class="text-center">NovaCare</h2>
                    {% csrf_token %}
                     <div class="mb-3">
                        <label for="phone" class="form-label">Phone Number:</label>
                        <input type="tel" class="form-control" id="phone" name="phone" value="{{ detail.phone_number }}" required>
                     </div>
                     <div class="mb-3">
                         <label for="amount" class="form-label">Amount:</label>
                         <input type="number" class="form-control" id="amount" name="amount" value="amount" required>
                     </div>
                    
                    <button type="submit" class="btn btn-primary w-100">Make Payment</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>