NovaCare/urls.py
from django.contrib import admin
from django.urls import path, include

from main_app import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('emergency/services/', views.emergency_services, name='emergency_services'),
    path('inpatient/services/', views.inpatient_services, name='inpatient_services'),
    path('outpatient/services/', views.outpatient_services, name='outpatient_services'),
    path('surgical/services/', views.surgical_services, name='surgical_services'),
    path('maternity/services/', views.maternity_services, name='maternity_services'),
    path('careers/', views.careers, name='careers'),


    path('novacare/', include('user_management.urls')),
    path('novacare/', include('payments_app.urls')),

    path('admin/', admin.site.urls),
]

user_management/urls.py
from django.urls import  path
from user_management import views

from NovaCare import settings
from django.conf.urls.static import static

app_name = 'user_management'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.signout_user, name='logout'),

    path('password-reset/', views.password_reset_request, name='password_reset_request'),
    path('reset-password-confirm/<str:token>/', views.password_reset_confirm, name='password_reset_confirm'),


    path('portal/', views.dashboard, name='dashboard'),
    path('staff/', views.staff_dashboard, name='staff_dashboard'),
    path('users/', views.patient_dashboard, name='patient_dashboard'),

    path('user/details/<int:user_id>', views.user_details, name='user_details'),
    path('user/add/details', views.add_details, name='add_details'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/About.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    <title>NovaCare - About Us</title>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'CSS/about.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
         <div class="banner">
             <img src="{% static 'Images/banner.jpg' %}" alt="banner" class="img-fluid">
         </div>
    </div>
    
    {# OUR FOUNDERS #}
    <div class="container">
        <h2 class="text-center p-3 founders">Our Founders</h2>
        <div class="row offset-1">
                <div class="col-sm-5 our-founders">
                    <p class="founder-details">
                        Dr. Rashid Omari is a visionary medical professional dedicated to advancing 
                        healthcare standards through innovation and compassion. With years of experience 
                        and a deep commitment to patient care, he founded NovaCare to provide accessible 
                        and high-quality medical services to the community. Dr. Omari’s leadership and expertise 
                        inspire a culture of excellence, making NovaCare a trusted name in modern healthcare.
                    </p>
                    <img src="{% static 'Images/user2.png' %}" alt="user" class="img-fluid">
                    <p class="user-details">
                        <b>Dr. Rashid Omari</b> <br>
                        Founder
                    </p>
                </div>
                <div class="col-sm-5 our-founders">
                    <p class="founder-details">
                        Dr. Jennifer Lopez, the co-founder of NovaCare, is a renowned healthcare leader 
                        passionate about delivering patient-centered medical care. With extensive experience 
                        in clinical practice and healthcare management, she brings a unique perspective to NovaCare’s 
                        mission of excellence. Dr. Lopez’s dedication to innovation and community health plays a pivotal 
                        role in shaping the hospital’s commitment to superior care.
                    </p>
                    <img src="{% static 'Images/user1.png' %}" alt="user" class="img-fluid">
                    <p class="user-details">
                        <b>Dr. Jennifer Lopez</b> <br>
                        Co-Founder
                    </p>
                </div>
            </div>
    </div>
    
    {# OUR PHILOSOPHY #}
    <div class="container mb-4 pb-2">
        <h2 class="text-center p-3 our-philosophy">Our Philosophy</h2>
        <div class="row">
            <div class="col-sm-4">
                <div class="philosophy p-3">
                    <h3 class="text-center">Vision</h3>
                    <p class="philosophy-details">
                        To be a trusted leader in delivering compassionate, innovative, and 
                        accessible healthcare for all.
                    </p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="philosophy p-3">
                    <h3 class="text-center">Mission</h3>
                    <p class="philosophy-details">
                        To provide exceptional, patient-centered healthcare by combining 
                        advanced technology, skilled professionals, and a commitment to community 
                        well-being.
                    </p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="philosophy p-3">
                    <h3 class="text-center">Values</h3>
                    <ul>
                        <li class="pt-2">Professionalism</li>
                        <li class="pt-2">Respect</li>
                        <li class="pt-2">Integrity</li>
                        <li class="pt-2">Collaboration</li>
                        <li class="pt-2">Excellence</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    {# FOOTER #}
    <div class="footer">
        <div class="container pb-3">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="pt-3 about-us">NovaCare</h4>
                    <p class="motto">
                        Your Health, Our Commitment
                    </p>
                    <p class="description">
                        NovaCare is a state-of-the-art healthcare facility offering high-quality
                        medical services with compassion and precision. We specialize in various fields,
                        including general medicine, surgery, pediatrics, and diagnostics, ensuring comprehensive
                        care for all. With a dedicated team and advanced technology, NovaCare is committed to your
                        well-being and a healthier future.
                    </p>
                </div>
                <div class="col-sm-4 contacts">
                    <h4 class="pt-3 about-us">Contact Us</h4>
                    <p class="p-2">
                        <i class='bx bxs-map' style='color:#ffffff'  ></i>
                        Hospital Rd, Nairobi
                    </p>
                    <p class="p-2">
                        <i class='bx bxs-phone' style='color:#ffffff'  ></i>
                        +254 712345678
                    </p>
                    <p class="p-2">
                        <i class='bx bx-envelope' style='color:#ffffff'  ></i>
                        ncadmin@novacare.com
                    </p>
                </div>
                <div class="col-sm-4 partnership">
                    <h4 class="pt-3 about-us">Our Partners</h4>
                    <ul class="partners">
                        <li class="pt-2"> Care Hospital</li>
                        <li class="pt-2"> Getrude Children's Hospital</li>
                        <li class="pt-2"> Capital Hospital</li>
                        <li class="pt-2"> Pediatric Partners Hospital</li>
                    </ul>
                    
                     <a href="#banner" class="d-flex align-items-end justify-content-end pb-5">
                         <img src="{% static 'Images/up-arrow.png' %}" alt="arrow" class="img-fluid">
                     </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Careers.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    <title>NovaCare - Careers</title>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'CSS/careers.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/about.css' %}">
{% endblock %}

{% block content %}
    <div class="container mb-4">
        <div class="row">
            <div class="col-sm-8 careers">
                <h2 class="pt-3">Careers</h2>
                <p class="pb-2">
                    NovaCare Hospital is a Private Corporation whose vision is to be a 
                    world-class Treasured Hospital providing innovative and specialized healthcare. 
                    The Hospital seeks to recruit dynamic, highly motivated, innovative and experienced 
                    individuals to fill the following vacant positions.
                </p>
                <table class="table-sm table-bordered table-striped table-responsive mb-3">
                    <tr>
                        <th>NO.</th>
                        <th>POSITION</th>
                        <th>REF NO.</th>
                        <th>POS.</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Senior Director Clinical Services</td>
                        <td>NCH/NCD/10/1</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Director, Nursing Services</td>
                        <td>NCH/NCD/10/2</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Gynaecologist</td>
                        <td>NCH/NCD/10/3</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>Neurologist</td>
                        <td>NCH/NCD/10/4</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>ICT Specialist</td>
                        <td>NCH/NCD/10/5</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>Finance Manager</td>
                        <td>NCH/NCD/10/6</td>
                        <td>1</td>
                    </tr>
                </table>
                
                <p>
                    Interested applicants who meet the requirements of the listed vacancies are
                    invited to make applications. The application form together with a detailed
                    C.V listing the qualifications, experience, current responsibilities, copies 
                    of testimonials, and certificates are to be submitted at NovaCare Hospital
                    Central Registry situated in the Hospitals Administration block 
                    <b>on or before 14 <sup>th</sup> September 2025.</b>
                </p>
                
                <p>
                    The application can also be posted to the address below:
                </p>
                <p class="text-center">
                    <b>The Chief Executive Officer</b> <br>
                    <b>NovaCare Hospital</b> <br>
                    <b>P.0 Box 25631-00202</b> <br>
                    <b>Nairobi</b>
                </p>
            </div>
        </div>
    </div>
    
    <div class="container mb-5 pb-5">
        <div class="row">
            <div class="col-sm-8 more-info">
                <p>
                    "NovaCare Hospital is an equal opportunity employer and qualified
                    candidates with disabilities are encouraged to apply".
                </p>
                
                <p>
                    <b>NB:</b>
                </p>
                
                <ol type="1">
                    <li>
                        NovaCare Hospital <b>DOES NOT</b> charge <b>ANY FEES</b> for application
                    </li>
                    <li>
                        Only shortlisted candidates will be contacted through telephone number 0712345678
                    </li>
                    <li>
                        Successful candidate will be required to submit the document listed below to comply with 
                        the requirements of Chapter Six (6) of the Constitution of Kenya,2010: – 
                    </li>
                </ol>
                
                <ul style="list-style-type: disc">
                    <li>
                        <b>A certificate of good conduct from the National Police Service</b>
                    </li>
                    <li>
                        <b>EACC Clearance</b>
                    </li>
                    <li>
                        <b>Credit Reference Bureau Clearance</b>
                    </li>
                    <li>
                        <b>HELB Compliance</b>
                    </li>
                    <li>
                        <b>KRA Tax Compliance </b>
                    </li>
                </ul>
                
                <p class="disclaimer">
                    “ANY FORM OF CANVASSING WILL LEAD TO AUTOMATIC DISQUALIFICATION”
                </p>
                
                <p class="department-head">
                    <b>EVEREST S. OSWALD, CBS, EBS</b> <br>
                    <b class="role">CHIEF EXECUTIVE OFFICER</b>
                </p>
            </div>
        </div>
    </div>
    
    {# FOOTER #}
    <div class="footer">
        <div class="container pb-3">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="pt-3 about-us">NovaCare</h4>
                    <p class="motto">
                        Your Health, Our Commitment
                    </p>
                    <p class="description">
                        NovaCare is a state-of-the-art healthcare facility offering high-quality
                        medical services with compassion and precision. We specialize in various fields,
                        including general medicine, surgery, pediatrics, and diagnostics, ensuring comprehensive
                        care for all. With a dedicated team and advanced technology, NovaCare is committed to your
                        well-being and a healthier future.
                    </p>
                </div>
                <div class="col-sm-4 contacts">
                    <h4 class="pt-3 about-us">Contact Us</h4>
                    <p class="p-2">
                        <i class='bx bxs-map' style='color:#ffffff'  ></i>
                        Hospital Rd, Nairobi
                    </p>
                    <p class="p-2">
                        <i class='bx bxs-phone' style='color:#ffffff'  ></i>
                        +254 712345678
                    </p>
                    <p class="p-2">
                        <i class='bx bx-envelope' style='color:#ffffff'  ></i>
                        ncadmin@novacare.com
                    </p>
                </div>
                <div class="col-sm-4">
                    <h4 class="pt-3 about-us">Our Partners</h4>
                    <ul class="partners">
                        <li class="pt-2"> Care Hospital</li>
                        <li class="pt-2"> Getrude Children's Hospital</li>
                        <li class="pt-2"> Capital Hospital</li>
                        <li class="pt-2"> Pediatric Partners Hospital</li>
                    </ul>
                    
                    <a href="#banner" class="d-flex align-items-end justify-content-end pb-5">
                         <img src="{% static 'Images/up-arrow.png' %}" alt="arrow" class="img-fluid">
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Contact.html
{% extends 'master.html' %}

{% block title %}
    <title>Contact Us</title>
{% endblock %}

{% block content %}
{% endblock %}

templates/Home.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    <title>NovaCare - Home</title>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'CSS/home.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
         <div class="banner">
             <img src="{% static 'Images/banner.jpg' %}" alt="banner" class="img-fluid">
         </div>
    </div>

    {# OUR SERVICES #}
    <div class="container">
         <h2 class="text-center p-3 services">Our Services</h2>
         <div class="row">
             <div class="col-sm-3">
                 <div class="service-box p-3">
                     <h3 class="text-center">Emergency Services</h3>
                     <div class="details">
                         <p>
                             NovaCare provides immediate care for acute injuries,
                             illnesses, and life-threatening conditions. Staffed with
                             emergency physicians, nurses, and other healthcare professionals,
                             this department operates 24/7 to handle emergencies such as trauma,
                             heart attacks, strokes, and accidents
                         </p>
                     </div>
                 </div>
             </div>

             <div class="col-sm-3">
                 <div class="service-box p-3">
                     <h3 class="text-center">Inpatient & Outpatient Services</h3>
                     <div class="details">
                         <p>
                             We offer comprehensive healthcare services providing round-the-clock care for
                             admitted patients (inpatient) and convenient same-day treatments, diagnostics,
                             and consultations (outpatient), ensuring seamless and personalized medical care
                             for all needs.
                         </p>
                     </div>
                 </div>
             </div>
             <div class="col-sm-3">
                 <div class="service-box p-3">
                     <h3 class="text-center">Surgical Services</h3>
                     <div class="details">
                         <p>
                             Our surgical services encompass preoperative, operative, and postoperative care
                             for patients undergoing surgeries. This includes operating rooms equipped with
                             advanced technology, skilled surgeons, anesthetists, and support staff to perform
                             procedures ranging from minor surgeries to complex operations.
                         </p>
                     </div>
                 </div>
             </div>
             <div class="col-sm-3">
                 <div class="service-box p-3">
                     <h3 class="text-center">Maternity & Neonatal Services</h3>
                     <div class="details">
                         <p>
                             This focuses on the care of pregnant women, childbirth, and newborn babies.
                             It includes services such as prenatal care, labor and delivery, postnatal care,
                             and neonatal intensive care units (NICUs) for premature or critically ill newborns.
                         </p>
                     </div>
                 </div>
             </div>
         </div>
    </div>

    {# ABOUT US #}
    <div class="container about-container mt-4 pb-3">
        <h2 class="text-center p-3 about-us">About Us</h2>
        <div class="row">
            <div class="col-sm-3">
                <div class="about-section-img d-flex justify-content-center">
                    <img src="{% static 'Images/bed.png' %}" alt="bed" class="img-fluid">
                </div>
                <div class="capacity d-flex justify-content-center pt-2">
                    1800
                </div>
                <div class="item d-flex justify-content-center">
                    <p class="text-white">Bed Capacity</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="about-section-img d-flex justify-content-center">
                    <img src="{% static 'Images/employees.png' %}" alt="bed" class="img-fluid">
                </div>
                <div class="capacity d-flex justify-content-center pt-2">
                    6000
                </div>
                <div class="item d-flex justify-content-center">
                    <p class="text-white">Employees</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="about-section-img d-flex justify-content-center">
                    <img src="{% static 'Images/years.png' %}" alt="bed" class="img-fluid">
                </div>
                <div class="capacity d-flex justify-content-center pt-2">
                    25
                </div>
                <div class="item d-flex justify-content-center">
                    <p class="text-white">Years of Service</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="about-section-img d-flex justify-content-center">
                    <img src="{% static 'Images/clinic.png' %}" alt="bed" class="img-fluid">
                </div>
                <div class="capacity d-flex justify-content-center pt-2">
                    16
                </div>
                <div class="item d-flex justify-content-center">
                    <p class="text-white">Clinics</p>
                </div>
            </div>
        </div>
    </div>
    
    {# OUR PARTNERS #}
    <div class="container pb-3">
         <h2 class="text-center p-3 services">Our Partners</h2>
         <div class="row d-flex align-items-center">
             <div class="col-sm-3">
                 <div class="partners-img d-flex justify-content-center align-items-center">
                     <img src="{% static 'Images/partner04.webp' %}" alt="logo" class="img-fluid">
                 </div>
             </div>
             <div class="col-sm-3">
                 <div class="partners-img d-flex justify-content-center align-items-center">
                     <img src="{% static 'Images/partner03.png' %}" alt="logo" class="img-fluid">
                 </div>
             </div>
             <div class="col-sm-3">
                 <div class="partners-img d-flex justify-content-center align-items-center">
                     <img src="{% static 'Images/partner02.webp' %}" alt="logo" class="img-fluid">
                 </div>
             </div>
             <div class="col-sm-3">
                 <div class="partners-img d-flex justify-content-center align-items-center">
                     <img src="{% static 'Images/partner01.png' %}" alt="logo" class="img-fluid">
                 </div>
             </div>
         </div>
    </div>

    {# FOOTER #}
    <div class="footer">
        <div class="container pb-3">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="pt-3 about-us">NovaCare</h4>
                    <p class="motto">
                        Your Health, Our Commitment
                    </p>
                    <p class="description">
                        NovaCare is a state-of-the-art healthcare facility offering high-quality
                        medical services with compassion and precision. We specialize in various fields,
                        including general medicine, surgery, pediatrics, and diagnostics, ensuring comprehensive
                        care for all. With a dedicated team and advanced technology, NovaCare is committed to your
                        well-being and a healthier future.
                    </p>
                </div>
                <div class="col-sm-4 contacts">
                    <h4 class="pt-3 about-us">Contact Us</h4>
                    <p class="p-2">
                        <i class='bx bxs-map' style='color:#ffffff'  ></i>
                        Hospital Rd, Nairobi
                    </p>
                    <p class="p-2">
                        <i class='bx bxs-phone' style='color:#ffffff'  ></i>
                        +254 712345678
                    </p>
                    <p class="p-2">
                        <i class='bx bx-envelope' style='color:#ffffff'  ></i>
                        ncadmin@novacare.com
                    </p>
                </div>
                <div class="col-sm-4">
                    <h4 class="pt-3 about-us">Our Partners</h4>
                    <ul class="partners">
                        <li class="pt-2"> Care Hospital</li>
                        <li class="pt-2"> Getrude Children's Hospital</li>
                        <li class="pt-2"> Capital Hospital</li>
                        <li class="pt-2"> Pediatric Partners Hospital</li>
                    </ul>

                    <a href="#banner" class="d-flex align-items-end justify-content-end pb-5">
                         <img src="{% static 'Images/up-arrow.png' %}" alt="arrow" class="img-fluid">
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/child_appointment_form.html
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <link rel="stylesheet" href="{% static 'CSS/child_form.css' %}">
  <title>NovaCare - Appointment</title>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-4 border mt-3 px-3 py-3 mb-3 register_form text-white">
                <form action="{% url 'add_client' %}" method="post">
                    <h2 class="company text-center">NovaCare</h2>
                    <h5 class="form-name mb-3">Appointment Booking</h5>
                    {% csrf_token %}
                    {{ form | crispy}}
                    <button class="btn btn-primary w-100">Book Appointment</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    {# added a favicon icon   #}
  <link rel="icon" href="{% static 'Images/nova.jpeg' %}">

  <link rel="stylesheet" href="{% static 'CSS/style.css' %}">


  {% block title %}
      <title>NovaCare</title>
  {% endblock %}

  {% block extra_css %}
  {% endblock %}

</head>
<body>
    <div class="container-fluid d-flex justify-content-center top-banner">
        <div class="banner" id="banner">
            <img src="{% static 'Images/nova.jpeg' %}" alt="logo" class="img-fluid banner-img" width="150px" height="150px">
        </div>
    </div>

    <nav class="navbar navbar-expand-sm navigation p-3">
      <div class="container-fluid">
        <a class="navbar-brand title" href="{% url 'home' %}">NovaCare</a>

        {#  Offcanvas toggler  #}
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>

        {# Offcanvas menu #}
        <div class="offcanvas offcanvas-end navigation-menu" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
           <div class="offcanvas-header">
               <h5 class="offcanvas-title" id="offcanvasNavbarLabel">NovaCare</h5>
               <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
           </div>
           <div class="offcanvas-body">
               <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'about' %}">About Us</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Services
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'emergency_services' %}">Emergency</a></li>
                            <li><a class="dropdown-item" href="{% url 'inpatient_services' %}">Inpatient</a></li>
                            <li><a class="dropdown-item" href="{% url 'outpatient_services' %}">Outpatient</a></li>
                            <li><a class="dropdown-item" href="{% url 'surgical_services' %}">Surgical</a></li>
                            <li><a class="dropdown-item" href="{% url 'maternity_services' %}">Maternity & Neonatal</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'careers' %}">Careers</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_management:login' %}">Portal</a>
                    </li>
               </ul>
                <div class="d-flex text-center pt-1">
                    <h5 class="text-white">Your Health, Our Commitment</h5>
                </div>
           </div>
        </div>
      </div>
    </nav>

    <div class="container">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show mt-2" role="alert">
                <p>{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>